@LogicalFitness.Api_HostAddress = http://localhost:5176

POST  {{LogicalFitness.Api_HostAddress}}/api/users/add
Accept: application/json
Content-Type: application/json

{
  "Id": "00000000-0000-0000-0000-000000000003",
  "Forename": "Test",
  "Surname": "User",
  "Email": "tes3.user@example.com",
  "DateOfBirth": "1990-01-01",
  "HeigthCm": 180,
  "WeightKg": 75.5,
  "CreatedAt": "2026-01-01T00:00:00Z",
  "UpdatedAt": "2026-01-01T00:00:00Z",
  "IsActive": true
}

###
