@LogicalFitnessApi_HostAddress = http://localhost:5176
POST  {{LogicalFitnessApi_HostAddress}}/api/users/add
Accept: application/json
Content-Type: application/json

{
  "Forename": "Test-{{$randomInt 1 1000}}",
  "Surname": "User-{{$randomInt 1 1000}}",
  "Email": "test-{{$guid}}@example.com",
  "DateOfBirth": "1900-09-12",
  "HeightCm": "{{$randomInt 140 195}}",
  "WeightKg": "{{$randomInt 40 150}}",
  "IsActive": true
}

